# Basic Information 
title: Hazel Torek
position: B.S. in Computer Science & Math
affiliation: Clemson University
affiliation_link: https://www.clemson.edu/
email: ctorek at clemson dot edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
# keywords: minimal light
description: Hazel is a third-year undergraduate at Clemson University studying computer science and math.
canonical: https://hazeltorek.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
#google_scholar: https://scholar.google.com/
cv_link: ./cv
github_link: https://github.com/hazeltorek/
linkedin: https://www.linkedin.com/in/hazel-torek/
lastfm: https://www.last.fm/user/hhhhazel
#twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/poster.jpg
#favicon: ./assets/img/favicon.png
#favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
